### ISSUE TITLE
CoreImage to PDF?

### ISSUE THREAD

**Issue by allen8300** [yourtion/Demo_CustomQRCode#1]
In this way, can you save your qrcode as pdf?

**Comment by yourtion** [comment]
You may try this. I found it at http://stackoverflow.com/questions/2445335/converting-uiimage-into-pdf-file/2445451#2445451

``` obj-c
-(void)createPDFfromUIView:(UIView*)aView saveToDocumentsWithFileName:(NSString*)aFilename
    {
        // Creates a mutable data object for updating with binary data, like a byte array
        NSMutableData *pdfData = [NSMutableData data];

        // Points the pdf converter to the mutable data object and to the UIView to be converted
        UIGraphicsBeginPDFContextToData(pdfData, aView.bounds, nil);
        UIGraphicsBeginPDFPage();

        // draws rect to the view and thus this is captured by UIGraphicsBeginPDFContextToData
        [aView.layer renderInContext:UIGraphicsGetCurrentContext()];

        // remove PDF rendering context
        UIGraphicsEndPDFContext();

        // Retrieves the document directories from the iOS device
        NSArray* documentDirectories = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask,YES);

        NSString* documentDirectory = [documentDirectories objectAtIndex:0];
        NSString* documentDirectoryFilename = [documentDirectory stringByAppendingPathComponent:aFilename];

        // instructs the mutable data object to write its context to a file on disk
        [pdfData writeToFile:documentDirectoryFilename atomically:YES];
        NSLog(@"documentDirectoryFileName: %@",documentDirectoryFilename);
    }
```

**Comment by allen8300** [comment]
Thanks so much for your reply, man. Sorry that I didn't describe it clearly.
In fact I want to export the QRCode to vector graphic(sag or pdf). Above method is common and right, which I also tried before, but cannot export our QRCode to vector graphic.

**Comment by yourtion** [comment]
I don't think the `CIImage` can be convert to vector graphic.If you want to get a vector QRCode you may try to use online api like http://keremerkan.net/qr-code-and-2d-code-generator/

**Comment by allen8300** [comment]
yeah, that's the topic I want to talk about with you. I tried many ways but all failed.

**Comment by yourtion** [comment]
Or you may try this online api to create svg or esp like this http://api.qrserver.com/v1/create-qr-code/?data=helloWorld&format=svg .

API Doc : http://goqr.me/api/doc/create-qr-code/

If you want to do it offline. You can use [ZXingObjC](https://github.com/TheLevelUp/ZXingObjC) and try to convert `ZXBitMatrix` to vector graphic.

**Comment by allen8300** [comment]
Yeah, you are right, I used ZXingObjc as foundation before, but seems it's not so flexible as CoreImage QRCode, also it's hard to extend, so I gave ZXingObjc up.
